# To learn fundamentals of fluxonium parameter

In [6]:
import numpy as np
import scipy.constants as cs
from matplotlib import pyplot as plt
from qutip import*
from scipy.special import eval_hermite as hpoly
import scipy.constants as cst
import sys

from Fluxonium_hamiltonians import Single_small_junction as fluxonium
import matplotlib as mpl

In [7]:
# %matplotlib inline # plot the figure inside the Jupyter Notebook
%matplotlib tk
# plot the figure in a pop out window. It looks very big

## This is going to describe the three parameters from fluxonium based on design
$$\LARGE{\hat{H}/\hbar = 4E_{C} -E_{J}\cos{\hat\phi}+\frac{1}{2}E_{L}(\hat\phi+\phi_{\rm ext})^2}$$, where

$$\LARGE{E_{c} = \frac{e^2}{2C}}$$, C is the total capacitance
$$\LARGE{E_{J} = \frac{I_{0s}\Phi_0}{2\pi}}$$, $I_{0s}$ is the critical current of the small junction
$$\LARGE{E_{L} = \frac{I_{0a}\Phi_0}{N\times 2\pi}}$$ $I_{0a}$ is the critical current of one junction of the JJ array and N is the number of the junctions in the JJ array

In [44]:
# Ec, Ej, El, in units of GHz, get the spectrum
N = 30 #number of levels
E_J = 4 #Josephson energy, GHz
E_C = 1 #Charging energy, GHz
E_L = 1 #Inductive energy, GHz
level_num = 10
phi_ext = np.linspace(0,1,201)
energies = np.zeros((len(phi_ext), level_num))
states = np.zeros((len(phi_ext), level_num, N))
max_display_y = 10

In [45]:
for idx, phi in enumerate(phi_ext):
    H = fluxonium.bare_hamiltonian(N, E_L, E_C, E_J, phi*2*np.pi)
    energies[idx, :] = H.eigenenergies()[:level_num]

In [46]:
figpath = 'C:/Users/Chuanhong/OneDrive/Desktop/Projects/2023Fluxonium/Fluxonium_berkeley_repository_learning/FluxoniumSpectrum/'

In [48]:
plt.figure(figsize=[8,6])
plt.xlim([phi_ext[0], phi_ext[-1]])
plt.ylim([0, 10])
ft = 28
plt.xticks(fontsize=ft)
plt.yticks(fontsize=ft)
# plt.ylim([0,max_display_y])
plt.xlabel(r'$\varphi_\mathrm{ext}/2\pi$', fontsize = ft)
plt.ylabel('Energy (GHz)', fontsize = ft)
# plt.ylabel(r'$ \omega_{ij}/2\pi$  (GHz)')
# for idx in range(1,level_num):
#     plt.plot(phi_ext, energies[:,idx] - energies[:,0], linewidth = '3')
# for idx in range(2,level_num):
#     plt.plot(phi_ext, energies[:,idx]-energies[:,1], linewidth = '1', linestyle = '--')

res_freq = 7.1
plt.plot(phi_ext, energies[:,3] - energies[:,0], linewidth = '3', color='y', label='03')
plt.plot(phi_ext, (energies[:,2] - energies[:,0]), linewidth = '3', color='r', label='02')
plt.plot(phi_ext, energies[:,2] - energies[:,1], linewidth = '3',color='b', label='12')
plt.plot(phi_ext, energies[:,1] - energies[:,0], linewidth = '3', color='k', label='01')

# plt.plot(phi_ext, (energies[:,2] - energies[:,0])/2, linewidth = '3',color='k', label='02/2')
# plt.plot(phi_ext, energies[:,3] - energies[:,0]-res_freq, linewidth = '3')

# plt.plot(phi_ext, (energies[:,2] - energies[:,1])/2, linewidth = '1', linestyle = '-.')
# plt.plot(phi_ext, (energies[:,2] - energies[:,0])/2, linewidth = '1', linestyle = '-.')
# plt.plot(phi_ext, (energies[:,3] - energies[:,0])/2, linewidth = '1', linestyle = '-.')

# plt.axvline(x = 0.35)
# plt.ylim([0,18])
# plt.axhline(y=res_freq,linestyle = '--', color = 'orange')
# print (energies[101,3]-energies[101,0])
# plt.axvline(x=0.4,linestyle = '--', color = 'orange', linewidth = 1.0)
# plt.axvline(x=0,linestyle = '--', color = 'orange', linewidth = 1.0)
# plt.axvline(x=0.5,linestyle = '--', color = 'orange', linewidth = 1.0)
# plt.grid()

plt.tight_layout()
plt.legend(fontsize=20, loc = 1)
if 1:
    figname = 'Ej2Ec1El1.jpg'
    plt.savefig(figpath+figname)
# print(energies[100,1] - energies[100,0])
# print(energies[100,2] - energies[100,1])
# print((energies[100,2] - energies[100,1])/2)
# print (energies[100,2]-energies[100,1])

# plt.show()

## Matrix element

$$\LARGE{
\hat{\phi} = \frac{1}{\sqrt{2}}\left(\frac{8E_{C}}{E_{L}} \right)^{1/4} (\hat{a}^{\dagger} + a)
}$$

$$\LARGE{
\hat{n} = \frac{i}{\sqrt{2}}\left(\frac{E_{L}}{8E_{C}} \right)^{1/4} (\hat{a}^{\dagger} - a)
}$$

Operator in the matrix form. $$\LARGE{
    \hat{O}_{ij} \equiv \langle u_{i}| O | u_{j} \rangle
}
$$

$$\LARGE{
    \hat{O} = \begin{pmatrix}
    O_{11} & O_{12} & \cdots & O_{1j} &\cdots \\
    O_{21} & O_{22} & \cdots & O_{2j} &\cdots \\
    \cdots & \cdots & \cdots & \cdots &\cdots \\
    O_{i1} & O_{i2} & \cdots & O_{ij} &\cdots \\
    \end{pmatrix}
}
$$

the destruction and creation operator in matrix form, here (i, j) starts from (0, 0)

$$\LARGE{
    \hat{a} = \begin{pmatrix}
    0 & \sqrt{1} & 0 & 0 &\cdots \\
    0 & 0 & \sqrt{2} & 0 &\cdots \\
    0 & 0 & 0 & \sqrt{3} &\cdots \\
    \cdots & \cdots & \cdots & \cdots &\cdots \\
    0 & 0 & \cdots & \cdots  & \sqrt{j}  \\
    \end{pmatrix}
}
$$

$$\LARGE{
    \hat{a}^{\dagger} = \begin{pmatrix}
    0 & 0 & 0 & 0 &\cdots \\
    \sqrt{1} & 0 & 0 & 0 &\cdots \\
    0 & \sqrt{2} & 0 & 0 &\cdots \\
    0 & 0 & \sqrt{3} & 0 &\cdots \\
    \cdots & \cdots & \cdots & \cdots &\cdots \\
    0 & 0 & \cdots & \sqrt{i} &\cdots \\
    \end{pmatrix}
}
$$

In [2]:
N = 30 #number of levels
E_J = 4 #Josephson energy, GHz
E_C = 1 #Charging energy, GHz
E_L = 1 #Inductive energy, GHz

In [5]:
p_me = fluxonium.phase_matrix_element_Liu(3, 1, 1, 4, 0.5, 0, 1)
p_me

destroy(N)= Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
a= Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
phi= Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.         1.18920712 0.        ]
 [1.18920712 0.         1.68179283]
 [0.         1.68179283 0.        ]]
na= Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.+0.j         0.-0.42044821j 0.+0.j        ]
 [0.+0.42044821j 0.+0.j         0.-0.59460356j]
 [0.+0.j         0.+0.59460356j 0.+0.j        ]]
ope= Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[0.+0.5j        0.+1.18920712j 0.+0.j        

(-0.17907396992932306+0j)